package constant

//k8s
const (
	//主机
	ENV_APISERVER = "APISERVER"
	APISERVER     = "10.151.160.17:6443"

	//TLS证书
	//ENV_CA_DATA   = "CA_DATA"
	//ENV_CERT_DATA = "CERT_DATA"
	//ENV_KET_DATA  = "KET_DATA"

//	CA_DATA = `-----BEGIN CERTIFICATE-----
//MIIB0DCCATOgAwIBAgIJAI03SRLlwwmHMAoGCCqGSM49BAMCMBgxFjAUBgNVBAMM
//DWt1YmVybmV0ZXMtY2EwHhcNMTgwMzA5MDczODA4WhcNMjgwMzA2MDczODA4WjAY
//MRYwFAYDVQQDDA1rdWJlcm5ldGVzLWNhMIGbMBAGByqGSM49AgEGBSuBBAAjA4GG
//AAQAzPY1hDmaIo60i0NvuWR9i/oJewUVK3DpmnerjUnZuqNmyb4HbhyIn1a0h1TT
//Lj7PH9vQl26gVwHEsP7GD6t/v80BpAEWW14N5vUzI5XzNTEzRZP41mIL9HPGxjMf
//Un/nNwwOfmx4/VnIW24j3Il3kwkX1M22hvbrBdNO+mcagDEizrajIzAhMA8GA1Ud
//EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgKkMAoGCCqGSM49BAMCA4GKADCBhgJB
//ELZX8VS8/Y0TYKjfOoS1DP+pRGK1xMIrP9tyaulFXpgXhDh2R381SAlVz0obiyG3
//1XW8s1PBMEog90L4IsAWIBgCQVOrzXNdf2d4pbvjw4cDOaEaYfyRnFuDX57M+ugG
//bfnodiVQS1pHhGeRe4yfOj9q3TEksFtLdF+DS0vRr/FKtHW+
//-----END CERTIFICATE-----`
//	CERT_DATA = `-----BEGIN CERTIFICATE-----
//MIICCjCCAWugAwIBAgIJAMOD4SrTBB+IMAoGCCqGSM49BAMCMBgxFjAUBgNVBAMM
//DWt1YmVybmV0ZXMtY2EwHhcNMTgwMzA5MDc0MTAzWhcNMjgwMzA2MDc0MTAzWjBB
//MSYwJAYDVQQDDB1rdWJlLWFwaXNlcnZlci1rdWJlbGV0LWNsaWVudDEXMBUGA1UE
//CgwOc3lzdGVtOm1hc3RlcnMwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAAEA6Xt
//rseo6S1FmsIZV6RYEIpyh6/aGGbydSD952kmDEro7a2NdF5jKCy6BXebgf1ZFzsF
//tPKy9tRng5NSBkCqSwGY9qeVy+9Nxsf3TXFKeQSI/UvFNyBNJbY52AXgegtjofP8
//vwLHqAPQ/atHmd6RO0bjfSZhr51/m4i2npzlD+OSraMyMDAwCQYDVR0TBAIwADAO
//BgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwCgYIKoZIzj0EAwID
//gYwAMIGIAkIBDrNlFVXzJh67ccW+fvNkKmdNvUKwErY1Yl4vdpcT69JZ7f01zRku
//olXatgb1PheXkgBIkVHl9h8ka9T+8XtTIAoCQgCjzz6TSlgskx/jXgAKO0ArYZhl
//z0wvQ6VFvfUaQpaqQKV3RiRFP9WdyFJdIFjjSb5buvW87uwLvHPUvNxTVaYgkg==
//-----END CERTIFICATE-----`
//	KET_DATA = `-----BEGIN EC PRIVATE KEY-----
//MIHcAgEBBEIBQGRE+bushKQls4UTALit9PJ4WCw+K7R/NdYmrW47xfiBOlX+pUwy
//SCl70QP9IDxd/pjCyHiXzigZq7KhVty3JEWgBwYFK4EEACOhgYkDgYYABAAEA6Xt
//rseo6S1FmsIZV6RYEIpyh6/aGGbydSD952kmDEro7a2NdF5jKCy6BXebgf1ZFzsF
//tPKy9tRng5NSBkCqSwGY9qeVy+9Nxsf3TXFKeQSI/UvFNyBNJbY52AXgegtjofP8
//vwLHqAPQ/atHmd6RO0bjfSZhr51/m4i2npzlD+OSrQ==
//-----END EC PRIVATE KEY-----`


	//默认的证书文件名
	CA_FILE   = "ca.crt"
	CERT_FILE = "client.crt"
	KEY_FILE  = "client.key"
)

//日志级别
const (
	ENV_LOGLEVEL = "LOGLEVEL"
	LOGLEVEL     = "ERROR"
)
